### PR TITLE
Update 4.1

### PR DESCRIPTION
**Pull request by betocantu93**
- ember-cli-update to 4.1
- bump ember-mapbox-gl
- bump mapbox-gl
- update some strict mode breaking code

### CODE REVIEW

**Comment by allthesignals** [comment]
Also, I get this error with this addon:

`You specified a `"srcDir": /svg` which does not exist and did not specify `"allowEmpty": true`.`

Why? Ember source 3.19.

**Comment by betocantu93** [comment]
I think we ended up using ember auto import to import it directly

**Comment by kturney** [comment]
Sorry, but I'm not really maintaining any of the `ember-mapbox` family of packages anymore.

**Comment by betocantu93** [comment]
We actually did a big update to ember-mapbox-gl here

https://github.com/grodriguez85/ember-mapbox-gl

If anyone wants to give it a go, using it on prod atm

With additional features like a caching mechanism, it requires mapbox 2 AFAIK, and so a License

**Comment by betocantu93** [comment]
> Sorry, but I'm not really maintaining any of the `ember-mapbox` family of packages anymore.

We can actually maintain it, right @grodriguez85? 

Maybe not this particular package but ember-mapbox-gl

**Comment by allthesignals** [comment]
Great! @betocantu93 let me know if I can help. I might want to use it for some upgrades I'm working on.

**Comment by betocantu93** [comment]
We published a new package after several years of maintaining a fork from ember-mapbox-gl, it has some of our use cases like caching maps, and more...

https://github.com/prysmex/ember-mapbox-gl

It has more features and we will keep maintaining it for the foreseeable future there.

Most of the code was rewritten with modern ember, typescript and new concepts so it would be really hard to propagate upstream without proper ownership. 

Examples and attributions are on their way!

Under npm: @prysmex-engineering/ember-mapbox-gl

**Pull request closed without merging**
